apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: dpa
  namespace: open-cluster-management-backup
spec:
  backupLocations:
    - velero:
        config:
          profile: default
          region: eu-west-2
        credential:
          key: cloud
          name: cloud-credentials
        default: true
        objectStorage:
          bucket: <your-bucket-name>
          prefix: velero
        provider: aws
  configuration:
    restic:
      enable: false
    velero:
      defaultPlugins:
        - openshift
        - aws
        - kubevirt
      logLevel: debug
  snapshotLocations:
    - velero:
        config:
          profile: default
          region: eu-west-2
        provider: aws
